baseURL = "https://bogolyandras.com/"
title = "András Bögöly's Personal Homepage"
languageCode = "en-us"
enableRobotsTXT = true

DefaultContentLanguage = "en"
copyright = "Everything is mine"

[languages]
  [languages.en]
    LanguageName = "English"
    weight = 1
    linkedin = "https://www.linkedin.com/in/bogolyandras"
  [languages.de]
    title_suffix = "András Bögöly's Personal Homepage"
    LanguageName = "Deutsch"
    weight = 2
    linkedin = "https://de.linkedin.com/in/bogolyandras"
  [languages.hu]
    title_suffix = "Bögöly András honlapja"
    LanguageName = "Magyar"
    weight = 3
    linkedin = "https://hu.linkedin.com/in/bogolyandras"

[params]
  title_suffix = "András Bögöly's Personal Homepage"
  [params.navigation]
    help = "Help"
